### ISSUE TITLE
Check compatibility with phantomjs 2.1.1

### ISSUE THREAD

**Issue by jpnelson** [skatejs/web-components#11]
This happens in unit tests: 

```
    ERROR: 'TypeError: Attempting to configurable attribute of unconfigurable property.'
```

**Comment by mitermayer** [comment]
Whats the current state of this issue ?

**Comment by jpnelson** [comment]
@mitermayer I haven't had a look at this yet, I think a good first step would be to try to run the named slots test suite with phantomjs 2.1.1

**Comment by treshugart** [comment]
This is the problem: https://github.com/ariya/phantomjs/issues/13895. The issue is in named slots when trying to override anything on a DOM node.

**Comment by treshugart** [comment]
Closing this as I've opened a bug in named-slots to address it there.
