### ISSUE TITLE
Implement fix for safari 10 style recalc bug

### ISSUE THREAD

**Issue by treshugart** [skatejs/web-components#16]
https://bugs.webkit.org/show_bug.cgi?id=160331

**Comment by Hotell** [comment]
This didn't fix the issue. Styles are still not resolved properly in Safari 10 :( any ideas?

**Comment by treshugart** [comment]
@Hotell it should have and seems to be working for a separate case, but maybe there's something we missed. Can you reproduce it somewhere for us?

**Comment by Hotell** [comment]
sure just open it in safari. No styles applied 

https://plnkr.co/edit/apc2FDjb3nJ95B48Uqwk?p=preview

Safari: Version 10.0 (11602.1.50.0.10)

**Comment by treshugart** [comment]
Thanks for that, it seems to work on the use case in which Safari 10 breaks for us but definitely not in your example. I'll reopen and investigate.
