### ISSUE TITLE
Something wrong with minification in firefox?

### ISSUE THREAD

**Issue by jpnelson** [skatejs/web-components#18]
Compare
http://codepen.io/anon/pen/vXRRQr

with
http://codepen.io/anon/pen/bwvvOE

in firefox.

**Comment by treshugart** [comment]
Yeah, I was getting an error with `something.get` is not a function. The line is in named-slots where it refers to a `const` that should be a reference to a `WeakMap`. I wasn't able to get much further with it, though.

**Comment by treshugart** [comment]
I think this is resolved now as I've forced webpack to do both builds.
