### ISSUE TITLE
Errors in FF and Safari using UglifyJS 

### ISSUE THREAD

**Issue by alexreardon** [skatejs/web-components#21]
When running `skate-web-components` through UglifyJS I am getting a run time exception in firefox and safari. 

It seems like it is erroring out in the following dependency: https://github.com/Benvie/WeakMap

**Comment by alexreardon** [comment]
It looks like this is related to #18

**Comment by alexreardon** [comment]
We are using the standard webpack uglifyJS plugin:

``` js
plugins: [
  new webpack.optimize.UglifyJsPlugin({
        compress: {
            warnings: false,
        },
        output: {
            comments: true,
        },
    }),
]
```

**Comment by adevnadia** [comment]
You can temporarily fix it by setting `mangle: false, compress: false` in this plugin.

**Comment by treshugart** [comment]
Spoke to @alexreardon IRL and they are using latest, but this is still an issue.

**Comment by jpnelson** [comment]
The problem is in weakmap – it uses Function.prototype.name

You can workaround it now by putting:

```
mangle: {
    keep_fnames: true,
}
```

in your config, but we'll release a new version with a better weakmap dependency.

**Comment by alexreardon** [comment]
Is this all good now josh?

**Comment by jpnelson** [comment]
Yes, should be! If it's not let me know.
