### ISSUE TITLE
upload to a cdn?

### ISSUE THREAD

**Issue by EricBalingit** [skatejs/web-components#29]
I'm liking what I see so far and am excited to start tinkering with skatejs!  Seems the perfect way to move into web components for those who prefer a javascript api.

This may seem a strange request, but when I experiment with javascript I prefer to use the Khan Academy sand box for convenience.  They do allow code from github, though it's less friendly for beginners who may find an interest, but other options include cdnjs and jsdeliver.

If there is a production ready version of this script/bundle, would you be so kind as to upload it to one of the later options? :-)  Is it already there and I missed it?

Thanks in advance!

**Comment by adevnadia** [comment]
Why you can't use unpkg?
`https://unpkg.com/skatejs@latest/dist/` - seems like exactly what you're looking for. `index-with-deps.min.js` - bundle with all the dependencies, `index.min.js` - just skate.js

**Comment by EricBalingit** [comment]
@nadiam84 The KA sandbox blocks scripts from any source except google host, cdnjs and jsdeliver.  I can certainly fork, pull into a c9 project, build and push back to my fork, then use rawgit as I mentioned above, but I was asking for the general use case, i.e. visit one of the above cdns, search for the script and paste the link into ones project. :-)

**Comment by adevnadia** [comment]
@EricBalingit Ahh, got it! I'll look into it a bit later. Or maybe you can add it yourself? ;) Anyone can do that as far as I can see. Contributions are always welcome ;)

**Comment by EricBalingit** [comment]
@nadiam84 I certainly wouldn't mind that.  Never done it before though.  Thanks for the tip on unpkg.com, saved me some time. ;)  I'm gonna play for a bit for the moment, but I have a day off after tomorrow.  I'll see what I can do.  If I get stuck I'll come back here.

**Comment by treshugart** [comment]
The link @nadiam84 posted was to Skate. That one is how you correctly use it via Unpkg, however, this package exports all the polyfills in the main index so you can just do https://unpkg.com/skatejs-web-components.

I'm going to close this for now. I'd prefer to not have to maintain any extra CDN stuff since there's already Rawgit and Unpkg. If this becomes a blocker, maybe we can find an alternate resolution. Thanks!
