### ISSUE TITLE
ShadyCSS doesn't work in IE11

### ISSUE THREAD

**Issue by devopsmariocom** [skatejs/web-components#34]
The reason is because `<template>` is not implemented in IE11.

One can of course add template polyfill like here http://codepen.io/elmariofredo/pen/mRazLq but from my understanding it doesn't have much sense to have shadyCss but not template polyfill in skate-web-components package.

Please let me know what do you think.

**Comment by treshugart** [comment]
Happy to add it to make it IE11 compat. Woud you mind PR'ing? Seems you have the ability to easily test it at the moment.

**Comment by devopsmariocom** [comment]
Sure PR is on its way

**Comment by Hotell** [comment]
related https://github.com/webcomponents/shadycss/issues/51

**Comment by devopsmariocom** [comment]
done... sorry it took so long got stuck between my birthday party and "awesome" IE11 debug tools 😉

**Comment by treshugart** [comment]
Happy birthday! Thanks for the PR; reviewing now.
