### ISSUE TITLE
npm install skatejs-web-components is broken

### ISSUE THREAD

**Issue by camargo** [skatejs/web-components#36]
When installing the most recent version of `skatejs-web-components` with npm I'm getting the error:

`Invalid Package: expected @webcomponents/template but found template`.

Node version: `7.5.0`
Npm version: `4.1.2`

**Comment by treshugart** [comment]
Works if you use yarn. I think NPM is complaining that their name isn't `@webcomponents/template`, but just `template`: https://github.com/webcomponents/template/blob/master/package.json#L2

**Comment by treshugart** [comment]
PR open for `@webcomponents/template` https://github.com/webcomponents/template/pull/9. To work around it, you can just use Yarn.

**Comment by treshugart** [comment]
Going to close this now as this is an issue in the template polyfill. We could change the dep key here to be "template", but that'd be incorrect because there's already a package called "template".

**Comment by matthewrobb** [comment]
I think you should keep this issue open as it's likely hitting a lot of users and this issue would be helpful to have show up in the open issue list

**Comment by treshugart** [comment]
@matthewrobb sure no problem.

**Comment by treshugart** [comment]
This has been merged! We should now update it and then we can close this.

**Comment by devopsmariocom** [comment]
That's my mistake so sending fixing PR #39

**Comment by treshugart** [comment]
Ah no probs, it needed fixing anyways :)
