### ISSUE TITLE
missing/broken scope on shadydom callbacks

### ISSUE THREAD

**Issue by micahscopes** [skatejs/web-components#37]
Recently, I was hung up on a bug that was breaking basic event propagation in shadydoms.  Callbacks were being called without binding the relevant context.  I was using d3, which relies on `this` in callbacks.  This bug was fixed in a very simple way [here](https://github.com/webcomponents/shadydom/pull/67).  But as you can see, that pull request has been sitting around for 2 months now (along with quite a few others).

Maybe consider using [the cloudydom fork](https://github.com/matthewp/cloudydom)?

**Comment by treshugart** [comment]
@micahscopes lol, I was actually just talking with @matthewp about that. I think I will. It's easy to switch between them, if necessary. Happy to accept a PR for the change if you can manage one :)

**Comment by micahscopes** [comment]
When I try running `npm install` or `npm prepublish` for some reason I'm getting:

``` console
Executing pre-build scripts
sed: -e expression #1, char 1: unknown command: `"'
"window.customElements && eval(\`$(cat ./src/native-shim.js)\`);" > ./src/native-shim.js

/home/micah/Web/skatejs-web-components/node_modules/webpack-shell-plugin/lib/index.js:168
        throw error;
        ^
```

I was getting this error before I changed the dependencies. Not sure about it.

**Comment by treshugart** [comment]
You might need to update npm or something like that?

**Comment by micahscopes** [comment]
I'll give it a shot

**Comment by micahscopes** [comment]
I've upgraded node and npm, but am still getting that error.  It's hard for me to know what exactly it means, as I have always avoided learning sed!

Maybe this is relevant: http://stackoverflow.com/questions/8421314/bash-quote-behavior-and-sed

I'm working on debugging it.

**Comment by treshugart** [comment]
Hmm, I'm getting that when using `npm`. If you use `yarn` it works just fine (really odd)

**Comment by micahscopes** [comment]
Yup, `yarn` works for me.

**Comment by micahscopes** [comment]
Do you want the yarn lockfile too?  Not sure why that's in there, but I've never used yarn before, so I don't want to assume anything. I suppose if anything, it serves as a kind of log.

**Comment by matthewp** [comment]
I'm happy to transfer the repo to a more neutral org (meaning not under my personal account) if anyone wants it.

**Comment by treshugart** [comment]
Just sent an invite for you to join the skatejs org @matthewp so you can transfer over. You should have access to transfer the repo, but let me know if not.

**Comment by matthewp** [comment]
Here it is! https://github.com/skatejs/cloudydom
