### ISSUE TITLE
update native-shim?

### ISSUE THREAD

**Issue by micahscopes** [skatejs/web-components#42]
I was experiencing an issue with native-shim's implementation of setAttribute.  It was automatically lower-casing attribute names, which interfered with my svg application (svg elements have some important camelCase attributes).  Turns out this is fixed in newer versions of webcomponents/custom-elements (see here: https://github.com/webcomponents/custom-elements/issues/14)

In my fork of this repository, I've upgraded to a newer version of custom-elements (v1.0.0-alpha.4).  It fixed my problem and passed all the tests.  Mind if I do a pull request?  While I'm at it, I could also upgrade the cloudydom dependency to 1.0.2.

**Comment by treshugart** [comment]
Yep, pls bump!

**Comment by micahscopes** [comment]
hm, working on it now, except I'm having that sed issue again, this time with both yarn and npm!

**Comment by micahscopes** [comment]
Take care of by #43.
