### ISSUE TITLE
current published version relies on non-existent `cloudydom/src/env` path in newer versions of cloudydom

### ISSUE THREAD

**Issue by micahscopes** [skatejs/web-components#44]
might be nice to do another publish to npm soon, since the published version is dependent on cloudydom@^1.0.1.  for me this resolves to cloudydom@1.0.5, which no longer contains the file `cloudydom/src/env`.  It has been moved to `cloudydom/src/shadydom`, I believe.

https://github.com/skatejs/web-components/blob/v5.2.1/src/index.js#L39

**Comment by devopsmariocom** [comment]
well actually right now we have `*` version added in this commit https://github.com/skatejs/web-components/commit/b9532dc312dad278403e35d31e71d297066ae75d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R38 I'm new to NWB, so I'm not sure if that is some requirement or best practice. 

I would suggest to use exact versions as we are importing from internal structure which can easily change without major version change. What do you think @treshugart ?

**Comment by treshugart** [comment]
This was republished under @skatejs/web-components which reset the version numbers because semantic-release (didn't know until now) determines version numbers based on the package name, not the tags.

If you install `@skatejs/web-components` you should be fine.
