### ISSUE TITLE
Update to use webreflection/document-register-element

### ISSUE THREAD

**Issue by treshugart** [skatejs/web-components#7]
This allows us to use a versioned polyfill that even supports back to IE8. The in-built functionality that fills some Mutation Observer behaviour for unsupported browsers requires fixing, so including the Mutation Observer polyfill from webcomponents.js fixes it. When these issues are fixed in the v0 / v1 polyfill, we can remove the Mutation Observer fill.

**Comment by jpnelson** [comment]
lgtm

**Comment by jpnelson** [comment]
lgtm
